### ISSUE TITLE
Automatic Sync

### ISSUE THREAD

**Issue by FHeidger** [GINQO/Master-Item-Manager#19]
Hey,
is there a possibilty to synchronize the dimensions and measure by reload the data?
Actual, we have to synchronize them manually with the GINQO Master Item Manager - Object and with every single user.
We want to synchronize it automatically for all users. Is that possible?
Thx

**Comment by maxwellginqo** [comment]
Hello,

Currently we have no immediate plans for implementing automatic
synchronization triggered by a reload from the script.
However updating the Master Items by one individual user should update all
the Master Items for everybody else who uses the app, since Master Items
are a part of the application, not tied to an individual user.

Hopefully this addresses your question,
Maxwell.
Maxwell Marchand
Qlik Solutions Architect
GINQO Consulting Ltd.

email: ***@***.***
cell: 778-323-2132 | www.ginqo.com
